### ISSUE TITLE
Private Network Request

### ISSUE THREAD

**Issue by juanitoddd** [amcewen/HttpClient#13]
Hello !,
I am a newby to Arduino, just wanted to ask how could I send HTTP Request to a local IP address ? 
Say a computer on the same Network 
Thank you in advance

**Comment by amcewen** [comment]
The same way that you send one to a public network request.  If you only have the IP address rather than the name then you can just use the IP address directly.  For example, in SimpleHttpExample.ino if you change:
`const char kHostname[] = "arduino.cc";`
to
`const char kHostname[] = "192.168.0.1";`
then it should connect to a web server at address 192.168.0.1
